#!/bin/bash

set -e

DISK=$1
MIRROR=$2

DATE=$(date -d "`date +%Y%m01`" +%Y.%m.%d)
PATH="archlinux/iso/latest/archlinux-${DATE}-x86_64.iso"

/usr/bin/curl -sL "${MIRROR}/${PATH}" | /usr/bin/dd conv=fsync bs=4M of=${DISK}
