#!/bin/bash

set -e

DISK=$1
MIRROR=$2

PATH="archlinux/iso/latest"

HTML=`/usr/bin/curl -sL "${MIRROR}/${PATH}"`
FILENAME=`echo ${HTML} | /usr/bin/grep -o 'href="archlinux.*iso">' | /usr/bin/grep -o "archlinux.*iso"`
URL="${MIRROR}/${PATH}/${FILENAME}"

/usr/bin/curl -sL ${URL} | /usr/bin/dd conv=fsync bs=4M of=${DISK}
